index:
    path: /
    controller: App\Controller\ProductController::index

add:
    path: /admin/new-product
    controller: App\Controller\ProductController::add

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
